### ISSUE TITLE
segfault in TM1637Display.cpp on line 215

### ISSUE THREAD

**Issue by mwallner** [GrazerComputerClub/TM1637Display#1]
(no validity check on displayable characters)
https://github.com/mstroh76/TM1637Display/blob/master/TM1637Display.cpp#L215

**Comment by mstroh76** [comment]
http://www.cplusplus.com/reference/map/map/operator[]/
"If k does not match the key of any element in the container, the function inserts a new element with that key" 
Wird gewollt als leeres Element eingefügt!
